os: linux
language: node_js
node_js: 12
script:
- echo "Skipping tests"
before_deploy:
- npm run clean
- npm install
- npm run compile
- rm -rf node_modules/ && rm -rf src/
- npm clean-install --only=production
deploy:
  provider: heroku
  api_key:
    secure: Pg5hXsWWyyGQR9MSCMVZsqJbhUq50vUKN0dkqDrRUrzkd4qmP672nn2JRNdPEMd5DcL1Joqa7ghIG/fXIEwQsZ2eyzJQ6InuMrUapvOxmqM+chTpWyj6Qqt1BgSRN6qv0UpujteHuucDo18NjLU418mpd0Xei+kLfxp2CAraHe8ptT9k478/idIeKcsxTz0vn4ta9sfoLIH4wIMrWZeq6jNjEkNz87uqi0oNlGRof9ag0otVs4dlJM9RFoBISpohZVsVF4T0OZOflyq/2SjYBhmld92mpEnO17iLnpWY00ygSGUrg7h/xFhgo/QIYJLezWe7AigFkkAZ+3en0mmzIGiGnvbmuEIpWm8PXToZh1oCY0JhcSsKtsGduDFdyitJphz61teaMaQlqTWTfIa3wKgPRCr6//s+2jTpeutaOPgmt6E1ADZFaO+4YIwzitJeg2UK/KW8/ODuyQ4noY0I/cEo1oVAg76lSq/8QmV6P2z4FswHP8jwlLedEhUEtNHUPTLRawhSqz/uKzGPY9OQlsecOUH6KbYtCPvpu5sph+zFphPzHzO8jzjIfyhqgs34QkZ/y5r2QgymcxGKO7s42XSwiHmWiU9SYIIFsWwdgCVp9sJsTYjeX7yxzf02SKs/c6ijKnBDw1TFitplkpSRCUeG9HTyFypQd0HpInWJph4=
  cleanup: true
